name: CI Documentation

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-20.04

    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.9]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Give permission to run scripts
        run: chmod +x ./docs/scripts/doc8_style_check.sh

      - name: Install Dependencies
        working-directory: .
        run: ./configure --docs

      - name: Check Sphinx Documentation build minimally
        working-directory: ./docs
        run: |
          source ../venv/bin/activate
          sphinx-build -E -W source build

      - name: Check for documentation style errors
        working-directory: ./docs
        run: |
          source ../venv/bin/activate
          ./scripts/doc8_style_check.sh
